---
- hosts: front
  sudo: yes
  gather_facts: no
  tasks:
    - name: Nginx | Asenna
      yum: >
        name=http://nginx.org/packages/centos/6/x86_64/RPMS/nginx-1.6.0-2.el6.ngx.x86_64.rpm
        state=present

    - name: Nginx | Konfigurointi
      template: src=templates/nginx/default.conf.j2 dest=/etc/nginx/conf.d/default.conf
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

